# Generated by Django 5.0.6 on 2026-04-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed_down_mbps', models.FloatField(default=0)),
                ('speed_up_mbps', models.FloatField(default=0)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('olt', 'OLT'), ('cabinet', 'Distribution Cabinet'), ('access_point', 'Access Point'), ('splice_box', 'Splice / Junction Box'), ('pisowifi', 'PisoWifi Node'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('port_count', models.IntegerField(default=0, help_text='Max subscriber ports')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_nodes', to='routers.router')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('mt_password', models.CharField(blank=True, max_length=255)),
                ('mt_profile', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('dhcp', 'DHCP / IPoE'), ('static', 'Static')], default='pppoe', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mt_status', models.CharField(default='unknown', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('sms_opt_out', models.BooleanField(default=False)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_effective_from', models.DateField(blank=True, null=True)),
                ('cutoff_day', models.IntegerField(default=1, help_text='Day of month for billing cutoff (1-28)')),
                ('start_date', models.DateField(blank=True, help_text='Service start date', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('disconnected', 'Disconnected'), ('deceased', 'Deceased'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deceased_date', models.DateField(blank=True, null=True)),
                ('deceased_note', models.TextField(blank=True)),
                ('disconnected_date', models.DateField(blank=True, null=True)),
                ('disconnected_reason', models.TextField(blank=True)),
                ('portal_otp', models.CharField(blank=True, max_length=6)),
                ('portal_otp_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.plan')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='routers.router')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateField()),
                ('apply_mode', models.CharField(choices=[('next_only', 'Next Invoice Only'), ('all_unpaid', 'All Unpaid From Effective Date'), ('manual', 'Choose Manually')], default='next_only', max_length=20)),
                ('changed_by', models.CharField(default='admin', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscribers.plan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscribers.plan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriberNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_label', models.CharField(blank=True, max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='subscribers.networknode')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_assignment', to='subscribers.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriberUsageCutoffSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_cutoff_snapshots', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-cutoff_date'],
                'unique_together': {('subscriber', 'cutoff_date')},
            },
        ),
        migrations.CreateModel(
            name='SubscriberUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('reset_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_daily', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('subscriber', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SubscriberUsageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('rx_delta', models.BigIntegerField(default=0)),
                ('tx_delta', models.BigIntegerField(default=0)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('is_reset', models.BooleanField(default=False)),
                ('sampled_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_samples', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-sampled_at'],
                'indexes': [models.Index(fields=['subscriber', 'sampled_at'], name='subscribers_subscri_6c65f7_idx')],
            },
        ),
    ]
