# Generated by Django 5.0.6 on 2026-04-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='billing_due_days',
            field=models.IntegerField(blank=True, help_text='Optional per-subscriber due offset in days after cutoff.', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='If disabled, invoices and snapshots will not be generated for this subscriber.'),
        ),
    ]
