# Generated by Django 5.0.6 on 2026-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_billing_due_days_subscriber_is_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='suspension_hold_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='suspension_hold_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='suspension_hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='suspension_hold_until',
            field=models.DateTimeField(blank=True, help_text='Admin-approved extension of service access for overdue accounts.', null=True),
        ),
    ]
