# Generated by Django 5.0.6 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_subscriber_suspension_hold_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='cutoff_day',
            field=models.IntegerField(blank=True, help_text='Optional day of month for billing cutoff (1-28). Leave blank to use billing settings.', null=True),
        ),
    ]
