# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_alter_subscriber_cutoff_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='billing_type',
            field=models.CharField(
                choices=[('postpaid', 'Postpaid'), ('prepaid', 'Prepaid')],
                default='postpaid',
                help_text='Postpaid bills after service use; prepaid bills before service use.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='cutoff_day',
            field=models.IntegerField(
                blank=True,
                help_text='Optional day of month for billing cutoff (1-31). Leave blank to use billing settings.',
                null=True,
            ),
        ),
    ]
