# Generated by Django 5.0.6 on 2026-04-29 12:15

import re
from django.db import migrations, models


def normalize_phone_digits(phone):
    digits = re.sub(r'\D+', '', phone or '')
    if len(digits) == 11 and digits.startswith('09'):
        return f"63{digits[1:]}"
    if len(digits) == 10 and digits.startswith('9'):
        return f"63{digits}"
    return digits


def backfill_normalized_phone(apps, schema_editor):
    Subscriber = apps.get_model('subscribers', 'Subscriber')
    SubscriberOTP = apps.get_model('subscribers', 'SubscriberOTP')

    for subscriber in Subscriber.objects.all().only('pk', 'phone'):
        Subscriber.objects.filter(pk=subscriber.pk).update(
            normalized_phone=normalize_phone_digits(subscriber.phone),
        )

    for otp in SubscriberOTP.objects.all().only('pk', 'phone'):
        SubscriberOTP.objects.filter(pk=otp.pk).update(
            normalized_phone=normalize_phone_digits(otp.phone),
        )


def clear_normalized_phone(apps, schema_editor):
    Subscriber = apps.get_model('subscribers', 'Subscriber')
    SubscriberOTP = apps.get_model('subscribers', 'SubscriberOTP')
    Subscriber.objects.update(normalized_phone='')
    SubscriberOTP.objects.update(normalized_phone='')


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0005_subscriber_billing_type_and_cutoff_31'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='subscriberotp',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.RunPython(backfill_normalized_phone, clear_normalized_phone),
    ]
