# Generated by Django 5.0.6 on 2026-04-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_subscriber_normalized_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['username'], 'permissions': [('manage_subscriber_billing', 'Can manage subscriber billing fields'), ('manage_subscriber_lifecycle', 'Can suspend, reconnect, disconnect, mark deceased, and archive subscribers'), ('import_subscribers', 'Can sync or import subscribers from routers')]},
        ),
    ]
