# Generated by Django 5.0.6 on 2026-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_interfacetrafficcache'),
        ('subscribers', '0007_alter_subscriber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networknode',
            name='system_role',
            field=models.CharField(blank=True, choices=[('', 'Manual Field Node'), ('router_root', 'Router Root')], max_length=30),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='node_type',
            field=models.CharField(choices=[('router_site', 'Router Site'), ('olt', 'OLT'), ('cabinet', 'Distribution Cabinet'), ('access_point', 'Access Point'), ('splice_box', 'Splice / Junction Box'), ('pisowifi', 'PisoWifi Node'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='networknode',
            constraint=models.UniqueConstraint(condition=models.Q(('system_role', 'router_root')), fields=('router', 'system_role'), name='uniq_nms_router_root_node'),
        ),
    ]
