# Generated by Django 5.0.6 on 2026-05-08 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('export', 'DB Export / Backup'), ('import_validation', 'Import Validation'), ('restore_test', 'Restore Test')], default='export', max_length=30)),
                ('profile', models.CharField(choices=[('full', 'Full Database'), ('business_critical', 'Business Critical'), ('subscribers', 'Subscribers'), ('billing_payments', 'Billing and Payments'), ('accounting', 'Accounting'), ('network_nms', 'Network and NMS'), ('settings_content', 'Settings and Content')], default='full', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('compression', models.CharField(blank=True, max_length=20)),
                ('pg_dump_format', models.CharField(blank=True, max_length=20)),
                ('source_database', models.CharField(blank=True, max_length=255)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('error_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('run_database_backup', 'Can run database backups'), ('download_database_backup', 'Can download database backup files'), ('delete_database_backup', 'Can delete database backup files'), ('validate_database_backup', 'Can validate database backup imports'), ('run_restore_test', 'Can run backup restore tests')],
            },
        ),
    ]
