# Generated by Django 5.0.6 on 2026-05-16 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRestorePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_checksum_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=20)),
                ('maintenance_window_starts_at', models.DateTimeField(blank=True, null=True)),
                ('maintenance_window_ends_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_by_name', models.CharField(blank=True, max_length=255)),
                ('authorization_reference', models.CharField(blank=True, max_length=255)),
                ('rollback_plan', models.TextField(blank=True)),
                ('post_restore_validation_plan', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('current_state_backup_confirmed', models.BooleanField(default=False)),
                ('maintenance_window_confirmed', models.BooleanField(default=False)),
                ('scheduler_stop_confirmed', models.BooleanField(default=False)),
                ('writes_blocked_confirmed', models.BooleanField(default=False)),
                ('rollback_plan_confirmed', models.BooleanField(default=False)),
                ('post_restore_validation_confirmed', models.BooleanField(default=False)),
                ('preflight_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_restore_plans', to=settings.AUTH_USER_MODEL)),
                ('source_backup_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_restore_plans', to='backups.backupjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_production_restore_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'permissions': [('view_production_restore_plan', 'Can view production restore plans'), ('change_production_restore_plan', 'Can change production restore plans')],
            },
        ),
    ]
