# Generated by Django 5.0.6 on 2026-04-20 13:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('cutoff_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('current_cycle_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('frozen', 'Frozen')], default='draft', max_length=20)),
                ('source', models.CharField(default='scheduler', max_length=20)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_snapshots', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-cutoff_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('voided', 'Voided'), ('waived', 'Waived')], default='open', max_length=20)),
                ('plan_snapshot', models.CharField(blank=True, max_length=100)),
                ('rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('token', models.CharField(blank=True, max_length=32, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('void_reason', models.CharField(blank=True, choices=[('subscriber_deceased', 'Subscriber Deceased'), ('admin_adjustment', 'Admin Adjustment'), ('duplicate', 'Duplicate Invoice'), ('other', 'Other')], max_length=30)),
                ('void_note', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='BillingSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('current_charge', 'Current Cycle Charge'), ('previous_balance', 'Previous Balance'), ('credit', 'Credit'), ('adjustment', 'Adjustment')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.billingsnapshot')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('maya', 'Maya'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(default='admin', max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
