# Generated by Django 5.0.6 on 2026-04-29 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_unique_billing_periods'),
        ('subscribers', '0005_subscriber_billing_type_and_cutoff_31'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreditAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('refund_due', 'Refund Due'), ('refund_paid', 'Refund Paid'), ('forfeit', 'Credit Forfeited')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.CharField(default='system', max_length=100)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_adjustments', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
    ]
