# Generated by Django 5.0.6 on 2026-04-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('billing', '0003_accountcreditadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreditadjustment',
            name='expense_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_refund_adjustment', to='accounting.expenserecord'),
        ),
    ]
