# Generated by Django 5.0.6 on 2026-05-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_accountcreditadjustment_expense_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreditadjustment',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('maya', 'Maya'), ('other', 'Other')], max_length=20),
        ),
    ]
