# Generated by Django 5.0.6 on 2026-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='coverage_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='coverage_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_badge',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_primary_cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_primary_cta_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_secondary_cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_secondary_cta_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='payment_channels',
            field=models.TextField(blank=True, help_text='One payment channel per line'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='support_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
