# Generated by Django 5.0.6 on 2026-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_landingpage_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='about_card_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='about_card_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contact_card_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contact_card_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contact_section_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contact_section_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contact_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='coverage_card_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='coverage_section_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='coverage_section_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='coverage_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_banner_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_banner_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_empty_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_empty_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_empty_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_section_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_section_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='featured_plan_badge',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_stat_plans_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_stat_portal_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_stat_portal_value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_stat_support_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_highlights',
            field=models.TextField(blank=True, help_text='One inquiry highlight per line'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_info_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_info_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_info_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_section_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_section_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_submit_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_success_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='network_promise_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='network_promise_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='network_promise_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='operations_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='operations_points',
            field=models.TextField(blank=True, help_text='One operations highlight per line'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='payment_empty_notes',
            field=models.TextField(blank=True, help_text='One payment fallback note per line'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='payment_section_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='payment_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='plan_cta_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='plan_fallback_features',
            field=models.TextField(blank=True, help_text='One fallback feature per line'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='plans_section_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='plans_section_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='plans_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_actions_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_link_contact_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_link_contact_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_link_plans_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_link_plans_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_link_portal_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='quick_link_portal_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_1_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_1_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_2_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_2_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_3_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_3_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_card_3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_section_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_section_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
