# Generated by Django 5.0.6 on 2026-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_landingpage_about_card_eyebrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='admin_login_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='dashboard_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_full_name_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_full_name_placeholder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_message_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_message_placeholder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_mobile_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_mobile_placeholder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_plan_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_service_address_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='inquiry_service_address_placeholder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='logout_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='nav_contact_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='nav_coverage_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='nav_plans_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='nav_why_us_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='portal_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='portal_nav_label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
