# Generated by Django 5.0.6 on 2026-04-22 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticsServiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unsupported', 'Unsupported'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_present', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True)),
                ('source', models.CharField(default='system', max_length=50)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('current_payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_diagnostics_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-last_seen_at', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsIncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('detected', 'Detected'), ('updated', 'Updated'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('manually_resolved', 'Manually Resolved')], max_length=30)),
                ('message', models.TextField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics_incident_events', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='diagnostics.diagnosticsincident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
