# Generated by Django 5.0.6 on 2026-04-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bandwidth', 'Bandwidth / Upstream'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance'), ('salary', 'Salary'), ('utilities', 'Utilities'), ('office', 'Office Expenses'), ('other', 'Other Expense')], default='other', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('recorded_by', models.CharField(default='admin', max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('billing', 'Billing Payment'), ('connection_fee', 'Connection Fee'), ('installation', 'Installation Fee'), ('other', 'Other Income')], default='billing', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.CharField(default='system', max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_record', to='billing.payment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
