# Generated by Django 5.0.6 on 2026-05-06 08:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('branch_code', models.CharField(default='00000', max_length=10)),
                ('registered_address', models.TextField(blank=True)),
                ('taxpayer_type', models.CharField(choices=[('sole_proprietor', 'Sole Proprietor'), ('corporation', 'Corporation')], default='sole_proprietor', max_length=30)),
                ('tax_classification', models.CharField(choices=[('non_vat', 'Non-VAT'), ('vat', 'VAT')], default='non_vat', max_length=20)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('manage_accounting_setup', 'Can manage Accounting v2 setup')],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['entity', 'start_date'],
                'permissions': [('manage_accounting_periods', 'Can manage accounting periods')],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_mode', models.CharField(choices=[('loose_leaf_guides', 'Loose-leaf books and filing guides'), ('cas_disabled', 'CAS/CBA mode disabled'), ('eis_disabled', 'EIS mode disabled')], default='loose_leaf_guides', max_length=40)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('fiscal_year_start_day', models.PositiveSmallIntegerField(default=1)),
                ('setup_status', models.CharField(choices=[('not_started', 'Not Started'), ('foundation_ready', 'Foundation Ready'), ('live', 'Live')], default='not_started', max_length=30)),
                ('current_template_key', models.CharField(blank=True, max_length=80)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Accounting settings',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('direct_cost', 'Direct Cost'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense')], max_length=30)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entity', 'code'],
                'permissions': [('manage_chartofaccount', 'Can manage chart of accounts')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=40)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reviewed', 'Reviewed'), ('locked', 'Locked'), ('reversed', 'Reversed'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('billing', 'Billing'), ('payment', 'Payment'), ('expense', 'Expense'), ('opening_balance', 'Opening Balance'), ('adjustment', 'Adjustment')], default='manual', max_length=30)),
                ('source_document_number', models.CharField(blank=True, max_length=120)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'permissions': [('post_journalentry', 'Can post journal entries')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'ordering': ['journal_entry', 'line_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=80)),
                ('source_model', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('source_number', models.CharField(blank=True, max_length=120)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='accounting_one_active_entity'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.accountingentity'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounting.accountingentity'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.accountingentity'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.accountingentity'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='sourcedocumentlink',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_document_links', to='accounting.accountingentity'),
        ),
        migrations.AddField(
            model_name='sourcedocumentlink',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='accounting.journalentry'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('entity', 'fiscal_year', 'period_number'), name='accounting_unique_period_number'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('entity', 'start_date', 'end_date'), name='accounting_unique_period_dates'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='accounting_unique_account_code'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('entity', 'entry_number'), name='accounting_unique_journal_entry_number'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('journal_entry', 'line_number'), name='accounting_unique_journal_line_number'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit', Decimal('0.00')), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', Decimal('0.00'))), _connector='OR'), name='accounting_journal_line_one_side'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocumentlink',
            constraint=models.UniqueConstraint(fields=('entity', 'source_app', 'source_model', 'source_id'), name='accounting_unique_source_document_link'),
        ),
    ]
