# Generated by Django 5.0.6 on 2026-05-06 11:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingentity_accountingperiod_accountingsettings_and_more'),
        ('billing', '0004_accountcreditadjustment_expense_record'),
        ('subscribers', '0009_harden_subscriber_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSourcePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=80)),
                ('source_model', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('source_number', models.CharField(blank=True, max_length=120)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft Journal Created'), ('posted', 'Posted'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='blocked', max_length=20)),
                ('blocked_reason', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_postings', to='accounting.accountingentity')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_posting_records', to='accounting.journalentry')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_source_postings', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
                'permissions': [('review_accountingsourceposting', 'Can review accounting source postings')],
            },
        ),
        migrations.CreateModel(
            name='CustomerWithholdingTaxClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_withheld', models.DecimalField(decimal_places=2, max_digits=14)),
                ('withholding_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7)),
                ('atc', models.CharField(blank=True, max_length=30)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('payor_tin', models.CharField(blank=True, max_length=50)),
                ('payor_name', models.CharField(blank=True, max_length=255)),
                ('payor_address', models.TextField(blank=True)),
                ('certificate_number', models.CharField(blank=True, max_length=120)),
                ('certificate_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('customer_claimed', 'Customer Claimed'), ('pending_2307', 'Pending 2307'), ('received', '2307 Received'), ('validated', 'Validated'), ('applied_to_return', 'Applied to Return'), ('disallowed', 'Disallowed'), ('canceled', 'Canceled')], default='pending_2307', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_withholding_claims', to='accounting.accountingentity')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_withholding_claims', to='billing.payment')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_withholding_claims', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingsourceposting',
            constraint=models.UniqueConstraint(fields=('source_app', 'source_model', 'source_id'), name='accounting_unique_source_posting'),
        ),
    ]
