# Generated by Django 5.0.6 on 2026-05-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingsourceposting_customerwithholdingtaxclaim_and_more'),
        ('billing', '0004_accountcreditadjustment_expense_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWithholdingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.customerwithholdingtaxclaim')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_withholding_allocations', to='billing.invoice')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerwithholdingallocation',
            constraint=models.UniqueConstraint(fields=('claim', 'invoice'), name='accounting_unique_withholding_allocation'),
        ),
    ]
