# Generated by Django 5.0.6 on 2026-05-06 12:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_customerwithholdingallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingTaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('tax_family', models.CharField(choices=[('expanded_withholding_tax', 'Expanded Withholding Tax'), ('creditable_vat_withheld', 'Creditable VAT Withheld'), ('percentage_tax_withheld', 'Percentage Tax Withheld'), ('other_creditable_withholding', 'Other Creditable Withholding')], default='expanded_withholding_tax', max_length=40)),
                ('atc', models.CharField(blank=True, max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7)),
                ('basis', models.CharField(choices=[('gross_payment', 'Gross Payment'), ('vatable_base', 'VATable Base'), ('gross_invoice', 'Gross Invoice'), ('manual', 'Manual Amount')], default='gross_payment', max_length=30)),
                ('payor_type', models.CharField(choices=[('any', 'Any Payor'), ('private_withholding_agent', 'Private Withholding Agent'), ('top_withholding_agent', 'Top Withholding Agent'), ('government', 'Government / GOCC'), ('other', 'Other')], default='any', max_length=40)),
                ('supplier_taxpayer_type', models.CharField(choices=[('any', 'Any Supplier Type'), ('sole_proprietor', 'Sole Proprietor'), ('corporation', 'Corporation')], default='any', max_length=30)),
                ('supplier_tax_classification', models.CharField(choices=[('any', 'Any Tax Classification'), ('vat', 'VAT'), ('non_vat', 'Non-VAT')], default='any', max_length=20)),
                ('bir_reference', models.CharField(blank=True, max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withholding_tax_classes', to='accounting.accountingentity')),
            ],
            options={
                'ordering': ['entity', 'tax_family', 'code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customerwithholdingtaxclaim',
            name='withholding_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_withholding_claims', to='accounting.withholdingtaxclass'),
        ),
        migrations.AddConstraint(
            model_name='withholdingtaxclass',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='accounting_unique_withholding_tax_class_code'),
        ),
    ]
