# Generated by Django 5.0.6 on 2026-05-06 22:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_default_atc_codes(apps, schema_editor):
    from apps.accounting.atc_seed import DEFAULT_BIR_ATC_CODES

    atc_model = apps.get_model('accounting', 'AlphanumericTaxCode')
    for item in DEFAULT_BIR_ATC_CODES:
        defaults = {
            'description': item['description'],
            'tax_family': item['tax_family'],
            'taxpayer_type': item['taxpayer_type'],
            'rate': item['rate'],
            'rate_label': item['rate_label'],
            'bir_form': item['bir_form'],
            'payor_type': item['payor_type'],
            'source_reference': item['source_reference'],
            'source_url': item['source_url'],
            'is_active': item['is_active'],
            'notes': item['notes'],
        }
        atc_model.objects.update_or_create(code=item['code'], defaults=defaults)


def unseed_default_atc_codes(apps, schema_editor):
    from apps.accounting.atc_seed import DEFAULT_BIR_ATC_CODES

    atc_model = apps.get_model('accounting', 'AlphanumericTaxCode')
    atc_model.objects.filter(
        code__in=[item['code'] for item in DEFAULT_BIR_ATC_CODES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_withholdingtaxclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphanumericTaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('tax_family', models.CharField(choices=[('expanded_withholding_tax', 'Expanded Withholding Tax'), ('creditable_vat_withheld', 'Creditable VAT Withheld'), ('percentage_tax_withheld', 'Percentage Tax Withheld'), ('final_withholding_tax', 'Final Withholding Tax'), ('income_tax', 'Income Tax'), ('other', 'Other')], default='expanded_withholding_tax', max_length=40)),
                ('taxpayer_type', models.CharField(choices=[('individual', 'Individual'), ('corporation', 'Corporation'), ('both', 'Individual / Corporation'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7)),
                ('rate_label', models.CharField(blank=True, max_length=80)),
                ('bir_form', models.CharField(blank=True, max_length=120)),
                ('payor_type', models.CharField(choices=[('any', 'Any Payor'), ('private_withholding_agent', 'Private Withholding Agent'), ('top_withholding_agent', 'Top Withholding Agent'), ('government', 'Government / GOCC'), ('other', 'Other')], default='any', max_length=40)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tax_family', 'code'],
            },
        ),
        migrations.AddField(
            model_name='customerwithholdingtaxclaim',
            name='atc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_withholding_claims', to='accounting.alphanumerictaxcode'),
        ),
        migrations.AddField(
            model_name='withholdingtaxclass',
            name='atc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholding_tax_classes', to='accounting.alphanumerictaxcode'),
        ),
        migrations.RunPython(seed_default_atc_codes, unseed_default_atc_codes),
    ]
