# Generated by Django 5.0.6 on 2026-05-07 03:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alphanumerictaxcode_and_more'),
        ('subscribers', '0009_harden_subscriber_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoverPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutover_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reconciling', 'Reconciling'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('live', 'Live'), ('voided', 'Voided')], default='draft', max_length=30)),
                ('source_policy', models.CharField(choices=[('opening_balances_only_pre_cutover', 'Opening balances only before cutover'), ('source_backfill_review_only', 'Pre-cutover source backfill for review only'), ('manual', 'Manual policy')], default='opening_balances_only_pre_cutover', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('live_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cutover_plans', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutover_plans', to='accounting.accountingentity')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_cutover_plans', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cutover_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cutover_date', '-created_at'],
                'permissions': [('manage_cutoverplan', 'Can manage Accounting v2 cutover plan')],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Upload'), ('xlsx', 'XLSX Upload'), ('system_snapshot', 'System Snapshot')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('journal_created', 'Journal Created'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=30)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('validation_errors', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opening_balance_imports', to=settings.AUTH_USER_MODEL)),
                ('cutover_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_imports', to='accounting.cutoverplan')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_imports', to='accounting.accountingentity')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_imports', to='accounting.journalentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_opening_balance_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_openingbalanceimport', 'Can manage opening balance imports')],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('gl_control', 'GL Control'), ('subscriber_ar', 'Subscriber AR'), ('customer_advance', 'Customer Advance'), ('cash', 'Cash'), ('bank', 'Bank'), ('wallet_gateway', 'Wallet / Gateway'), ('ap_vendor', 'AP Vendor'), ('inventory', 'Inventory'), ('fixed_asset', 'Fixed Asset'), ('accumulated_depreciation', 'Accumulated Depreciation'), ('tax', 'Tax'), ('loan', 'Loan'), ('equity', 'Equity'), ('other', 'Other')], default='gl_control', max_length=40)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_object_type', models.CharField(blank=True, max_length=80)),
                ('source_object_id', models.CharField(blank=True, max_length=80)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error')], default='pending', max_length=20)),
                ('validation_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_lines', to='accounting.chartofaccount')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_lines', to='accounting.accountingentity')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.openingbalanceimport')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_lines', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['import_batch', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cutoverplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'voided'), _negated=True), fields=('entity',), name='accounting_one_active_cutover_plan'),
        ),
        migrations.AddConstraint(
            model_name='openingbalanceline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit', Decimal('0.00')), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', Decimal('0.00'))), _connector='OR'), name='accounting_opening_balance_line_one_side'),
        ),
    ]
