# Generated by Django 5.0.6 on 2026-05-07 04:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_cutoverplan_openingbalanceimport_openingbalanceline_and_more'),
        ('subscribers', '0009_harden_subscriber_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoverReconciliationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('reconciled', 'Reconciled'), ('voided', 'Voided')], default='generated', max_length=20)),
                ('ar_source_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ar_opening_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ar_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_source_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_opening_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('source_invoice_count', models.PositiveIntegerField(default=0)),
                ('source_credit_subscriber_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cutover_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_snapshots', to='accounting.cutoverplan')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutover_reconciliation_snapshots', to='accounting.accountingentity')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cutover_reconciliation_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'permissions': [('manage_cutoverreconciliationsnapshot', 'Can manage Accounting v2 cutover reconciliation snapshots')],
            },
        ),
        migrations.CreateModel(
            name='CutoverSubscriberBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(choices=[('subscriber_ar', 'Subscriber AR'), ('customer_advance', 'Customer Advance')], max_length=30)),
                ('source_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('opening_line_count', models.PositiveIntegerField(default=0)),
                ('source_references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('missing_opening', 'Missing Opening Balance'), ('missing_source', 'Opening Without Source'), ('difference', 'Difference')], default='matched', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutover_subscriber_balance_lines', to='accounting.accountingentity')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_lines', to='accounting.cutoverreconciliationsnapshot')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutover_balance_lines', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['balance_type', 'subscriber__username', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cutoversubscriberbalanceline',
            constraint=models.UniqueConstraint(fields=('snapshot', 'subscriber', 'balance_type'), name='accounting_unique_cutover_subscriber_balance_line'),
        ),
    ]
