# Generated by Django 5.0.6 on 2026-05-14 03:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_cutoverreconciliationsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoverBalanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('cash_on_hand', 'Cash on Hand'), ('bank_account', 'Bank Accounts'), ('wallet_gateway', 'Wallet / Gateway Clearing'), ('accounts_payable', 'Accounts Payable'), ('tax_balance', 'Tax Balances')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs Review'), ('reconciled', 'Reconciled'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('validation_errors', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cutover_balance_schedules', to=settings.AUTH_USER_MODEL)),
                ('cutover_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_schedules', to='accounting.cutoverplan')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutover_balance_schedules', to='accounting.accountingentity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cutover_balance_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cutover_plan', 'schedule_type'],
                'permissions': [('manage_cutoverbalanceschedule', 'Can manage Accounting v2 cutover balance schedules')],
            },
        ),
        migrations.CreateModel(
            name='CutoverBalanceScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('source_document_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error')], default='pending', max_length=20)),
                ('validation_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_balance_schedule_lines', to='accounting.chartofaccount')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutover_balance_schedule_lines', to='accounting.accountingentity')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.cutoverbalanceschedule')),
            ],
            options={
                'ordering': ['schedule', 'account__code', 'label', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cutoverbalanceschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'voided'), _negated=True), fields=('cutover_plan', 'schedule_type'), name='accounting_unique_active_cutover_balance_schedule'),
        ),
        migrations.AddConstraint(
            model_name='cutoverbalancescheduleline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit', Decimal('0.00')), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', Decimal('0.00'))), _connector='OR'), name='accounting_cutover_schedule_line_one_side'),
        ),
    ]
