# Generated by Django 5.0.6 on 2026-05-14 05:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_cutoverbalanceschedule_cutoverbalancescheduleline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoverbalancescheduleline',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cutoverbalancescheduleline',
            name='asset_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cutoverbalancescheduleline',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cutoverbalancescheduleline',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cutoverbalancescheduleline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='cutoverbalancescheduleline',
            name='unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cutoverbalancescheduleline',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cutoverbalanceschedule',
            name='schedule_type',
            field=models.CharField(choices=[('cash_on_hand', 'Cash on Hand'), ('bank_account', 'Bank Accounts'), ('wallet_gateway', 'Wallet / Gateway Clearing'), ('accounts_payable', 'Accounts Payable'), ('tax_balance', 'Tax Balances'), ('inventory', 'Inventory'), ('fixed_assets', 'Fixed Assets and Depreciation'), ('loans_payable', 'Loans Payable'), ('equity_balance', 'Equity Balances')], max_length=30),
        ),
    ]
