# Generated by Django 5.0.6 on 2026-05-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_cutoverbalancescheduleline_acquisition_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='closing_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('billing', 'Billing'), ('payment', 'Payment'), ('expense', 'Expense'), ('opening_balance', 'Opening Balance'), ('closing', 'Closing Entry'), ('adjustment', 'Adjustment')], default='manual', max_length=30),
        ),
    ]
