# Generated by Django 5.0.6 on 2026-05-15 00:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_accountingperiod_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingReportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=120)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('pdf', 'PDF'), ('manifest', 'Manifest')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('canonical_filename', models.CharField(max_length=255)),
                ('canonical_sha256', models.CharField(max_length=64)),
                ('canonical_size', models.PositiveIntegerField(default=0)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_archives', to='accounting.accountingentity')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_report_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
                'permissions': [('view_accounting_report_archive', 'Can view accounting report archives')],
            },
        ),
    ]
