# Generated by Django 5.0.6 on 2026-05-15 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_accountingreportarchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APVendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('bill_number', models.CharField(max_length=120)),
                ('document_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft Journal'), ('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ap_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_vendor_bills_as_payable', to='accounting.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ap_vendor_bills', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_vendor_bills', to='accounting.accountingentity')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_vendor_bills_as_expense', to='accounting.chartofaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_vendor_bills', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
                'permissions': [('manage_apvendorbill', 'Can manage AP vendor bills')],
            },
        ),
        migrations.CreateModel(
            name='APVendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.apvendorbill')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_vendor_payments_as_cash', to='accounting.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ap_vendor_payments', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_vendor_payments', to='accounting.accountingentity')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_vendor_payments', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='apvendorbill',
            constraint=models.UniqueConstraint(fields=('entity', 'vendor_name', 'bill_number'), name='accounting_unique_ap_vendor_bill'),
        ),
    ]
