# Generated by Django 5.0.6 on 2026-05-15 08:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_ap_vendor_bill_base_amount(apps, schema_editor):
    APVendorBill = apps.get_model('accounting', 'APVendorBill')
    for bill in APVendorBill.objects.all().iterator():
        bill.base_amount = bill.amount
        bill.save(update_fields=['base_amount'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_apvendorbill_apvendorpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apvendorbill',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='apvendorbill',
            name='input_vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='apvendorbill',
            name='tax_treatment',
            field=models.CharField(choices=[('non_vat', 'Non-VAT'), ('vat', 'VAT'), ('vat_exempt', 'VAT Exempt'), ('zero_rated', 'Zero-Rated')], default='non_vat', max_length=20),
        ),
        migrations.AddField(
            model_name='apvendorbill',
            name='void_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_ap_vendor_bills', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='apvendorbill',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apvendorbill',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apvendorbill',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_ap_vendor_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apvendorbill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft Journal'), ('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('void_pending', 'Void Pending'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
        migrations.RunPython(backfill_ap_vendor_bill_base_amount, noop_reverse),
    ]
