# Generated by Django 5.0.6 on 2026-05-15 08:56

import apps.accounting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_apvendorbill_base_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('registered_name', models.CharField(blank=True, max_length=255)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('registered_address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('tax_classification', models.CharField(choices=[('unknown', 'Unknown'), ('non_vat', 'Non-VAT'), ('vat', 'VAT'), ('vat_exempt', 'VAT Exempt'), ('zero_rated', 'Zero-Rated')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_ap_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_vendors_as_default_payable', to='accounting.chartofaccount')),
                ('default_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_vendors_as_default_expense', to='accounting.chartofaccount')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_vendors', to='accounting.accountingentity')),
            ],
            options={
                'ordering': ['name', 'code'],
                'permissions': [('manage_apvendor', 'Can manage AP vendors')],
            },
        ),
        migrations.AddField(
            model_name='apvendorbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.apvendor'),
        ),
        migrations.CreateModel(
            name='APVendorBillAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('supplier_invoice', 'Supplier Invoice'), ('receipt', 'Receipt'), ('statement', 'Statement'), ('supporting_document', 'Supporting Document'), ('other', 'Other')], default='supplier_invoice', max_length=30)),
                ('file', models.FileField(upload_to=apps.accounting.models.ap_vendor_bill_attachment_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.apvendorbill')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_vendor_bill_attachments', to='accounting.accountingentity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ap_vendor_bill_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'permissions': [('manage_apvendorbillattachment', 'Can manage AP vendor bill attachments')],
            },
        ),
        migrations.AddConstraint(
            model_name='apvendor',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='accounting_unique_ap_vendor_code'),
        ),
    ]
