# Generated by Django 5.0.6 on 2026-05-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_ap_vendor_payment_status(apps, schema_editor):
    APVendorPayment = apps.get_model('accounting', 'APVendorPayment')
    for payment in APVendorPayment.objects.select_related('journal_entry').all().iterator():
        if payment.journal_entry_id and payment.journal_entry.status == 'posted':
            payment.status = 'posted'
            payment.save(update_fields=['status'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_apvendor_apvendorbill_vendor_apvendorbillattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apvendorpayment',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_ap_vendor_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='settlement_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='settlement_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='settlement_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched')], default='unmatched', max_length=20),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft Journal'), ('posted', 'Posted'), ('void_pending', 'Void Pending'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='void_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_ap_vendor_payments', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apvendorpayment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_ap_vendor_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_ap_vendor_payment_status, noop_reverse),
    ]
