# Generated by Django 5.0.6 on 2026-05-15 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_apvendorpayment_matched_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingreportarchive',
            name='archive_file',
            field=models.FileField(blank=True, upload_to='accounting/report_archives/files/'),
        ),
        migrations.AddField(
            model_name='accountingreportarchive',
            name='package_file',
            field=models.FileField(blank=True, upload_to='accounting/report_archives/packages/'),
        ),
        migrations.AddField(
            model_name='accountingreportarchive',
            name='package_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='accountingreportarchive',
            name='package_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AccountingReportPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_presets', to='accounting.accountingentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_report_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_key', 'name', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingreportpreset',
            constraint=models.UniqueConstraint(fields=('entity', 'user', 'report_key', 'name'), name='accounting_unique_report_preset_name'),
        ),
    ]
