# Generated by Django 5.0.6 on 2026-05-15 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingreportarchive_archive_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='require_period_close_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='require_period_reopen_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountingPeriodCloseChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_close_checklist_items', to='accounting.accountingentity')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_checklist_items', to='accounting.accountingperiod')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriodWorkflowReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('close', 'Close'), ('reopen', 'Reopen')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('consumed', 'Consumed')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_workflow_reviews', to='accounting.accountingentity')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_reviews', to='accounting.accountingperiod')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_accounting_period_workflow_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accounting_period_workflow_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'permissions': [('review_accountingperiodworkflowreview', 'Can review accounting period workflow requests')],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingperiodclosechecklistitem',
            constraint=models.UniqueConstraint(fields=('period', 'key'), name='accounting_unique_period_close_checklist_item'),
        ),
    ]
