# Generated by Django 5.0.6 on 2026-05-15 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_accountingsettings_require_period_close_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('bank', 'Bank'), ('wallet', 'Wallet'), ('gateway', 'Gateway')], max_length=20)),
                ('statement_reference', models.CharField(max_length=120)),
                ('statement_start_date', models.DateField()),
                ('statement_end_date', models.DateField()),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reconciling', 'Reconciling'), ('reconciled', 'Reconciled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_statement_imports', to='accounting.chartofaccount')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_statement_imports', to='accounting.accountingentity')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_cash_statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_end_date', '-imported_at', '-id'],
                'permissions': [('manage_cashstatementimport', 'Can manage cash statement imports')],
            },
        ),
        migrations.CreateModel(
            name='CashStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('transaction_date', models.DateField()),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('exception', 'Exception')], default='unmatched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_statement_lines', to='accounting.accountingentity')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.cashstatementimport')),
            ],
            options={
                'ordering': ['import_batch', 'line_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_reconciliation_matches', to='accounting.accountingentity')),
                ('journal_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_reconciliation_match', to='accounting.journalline')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_cash_reconciliation_lines', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounting.cashstatementimport')),
                ('statement_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='accounting.cashstatementline')),
            ],
            options={
                'ordering': ['-matched_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('unmatched_receipt', 'Unmatched Receipt'), ('unmatched_disbursement', 'Unmatched Disbursement'), ('timing_item', 'Timing Item')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_reconciliation_exceptions', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_reconciliation_exceptions', to='accounting.accountingentity')),
                ('journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_reconciliation_exceptions', to='accounting.journalline')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cash_reconciliation_exceptions', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='accounting.cashstatementimport')),
                ('statement_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='accounting.cashstatementline')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashstatementimport',
            constraint=models.UniqueConstraint(fields=('entity', 'cash_account', 'statement_reference'), name='accounting_unique_cash_statement_import'),
        ),
        migrations.AddConstraint(
            model_name='cashstatementline',
            constraint=models.UniqueConstraint(fields=('import_batch', 'line_number'), name='accounting_unique_cash_statement_line_number'),
        ),
    ]
