# Generated by Django 5.0.6 on 2026-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_day', models.IntegerField(default=1)),
                ('due_days', models.IntegerField(default=7)),
                ('grace_period_days', models.IntegerField(default=3)),
                ('currency_symbol', models.CharField(default='PHP', max_length=10)),
                ('enable_auto_generate', models.BooleanField(default=False)),
                ('enable_auto_disconnect', models.BooleanField(default=False)),
                ('billing_mode', models.CharField(choices=[('legacy', 'Legacy Due Day'), ('cutoff_advance', 'Cutoff Advance Billing')], default='cutoff_advance', max_length=20)),
                ('billing_snapshot_mode', models.CharField(choices=[('auto', 'Auto - freeze immediately on cutoff'), ('draft', 'Draft - admin reviews before freezing'), ('manual', 'Manual - admin triggers snapshot')], default='auto', max_length=20)),
                ('draft_auto_freeze_hours', models.IntegerField(default=24)),
                ('billing_due_offset_days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RouterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_api_port', models.IntegerField(default=8728)),
                ('polling_interval_seconds', models.IntegerField(default=10)),
                ('sync_on_startup', models.BooleanField(default=False)),
                ('connection_timeout_seconds', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Router Settings',
            },
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaphore_api_key', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(default='ISPManager', max_length=11)),
                ('enable_billing_sms', models.BooleanField(default=False)),
                ('billing_sms_schedule', models.CharField(default='08:00', max_length=50)),
                ('billing_sms_days_before_due', models.IntegerField(default=3)),
                ('billing_sms_template', models.TextField(default='Hi {name}, your bill of {currency}{amount} is due on {due_date}. Pay here: {link}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mikrotik_auto_suspend', models.BooleanField(default=True, help_text='Automatically disable PPP secret on MikroTik when subscriber is suspended')),
                ('mikrotik_auto_reconnect', models.BooleanField(default=True, help_text='Automatically enable PPP secret on MikroTik when subscriber is reconnected')),
                ('archive_after_days', models.IntegerField(default=90, help_text='Auto-archive disconnected/deceased subscribers after this many days')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscriber Settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255)),
                ('chat_id', models.CharField(blank=True, max_length=100)),
                ('enable_notifications', models.BooleanField(default=False)),
                ('notify_new_subscriber', models.BooleanField(default=True)),
                ('notify_subscriber_status_change', models.BooleanField(default=True)),
                ('notify_router_status', models.BooleanField(default=True)),
                ('notify_billing_generated', models.BooleanField(default=True)),
                ('notify_payment_received', models.BooleanField(default=True)),
                ('notify_sms_sent', models.BooleanField(default=False)),
                ('notify_plan_change', models.BooleanField(default=True)),
                ('notify_settings_change', models.BooleanField(default=True)),
                ('notify_api_errors', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Settings',
            },
        ),
        migrations.CreateModel(
            name='UsageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('sampler_interval_minutes', models.IntegerField(default=5)),
                ('raw_retention_days', models.IntegerField(default=14)),
                ('daily_retention_days', models.IntegerField(default=365)),
                ('cutoff_snapshot_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usage Settings',
            },
        ),
    ]
