# Generated by Django 5.0.6 on 2026-04-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_smssettings_after_due_billing_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribersettings',
            name='auto_reconnect_after_full_payment',
            field=models.BooleanField(default=False, help_text='Automatically reconnect suspended subscribers after all open balances are fully paid'),
        ),
    ]
