# Generated by Django 5.0.6 on 2026-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_subscribersettings_auto_reconnect_after_full_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribersettings',
            name='disconnected_billing_policy',
            field=models.CharField(choices=[('preserve_balance', 'Preserve existing balance'), ('final_invoice', 'Generate final invoice'), ('waive_open_balances', 'Waive open balances')], default='preserve_balance', help_text='Billing action to apply when a subscriber is marked disconnected', max_length=30),
        ),
    ]
