# Generated by Django 5.0.6 on 2026-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_subscribersettings_disconnected_billing_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribersettings',
            name='disconnected_credit_policy',
            field=models.CharField(choices=[('preserve_credit', 'Preserve account credit'), ('mark_refund_due', 'Mark refund due'), ('forfeit_credit', 'Forfeit account credit')], default='preserve_credit', help_text='Credit action to apply when a disconnected subscriber has remaining account credit', max_length=30),
        ),
    ]
