# Generated by Django 5.0.6 on 2026-05-08 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_subscribersettings_mikrotik_status_auto_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_root', models.CharField(default='/opt/backups/ispmanager/db', max_length=500)),
                ('pg_dump_path', models.CharField(default='pg_dump', max_length=255)),
                ('filename_prefix', models.CharField(default='ispmanager', max_length=80)),
                ('manual_backups_enabled', models.BooleanField(default=False)),
                ('partial_backups_enabled', models.BooleanField(default=False)),
                ('allow_backup_download', models.BooleanField(default=False)),
                ('allow_backup_delete', models.BooleanField(default=False)),
                ('retention_keep_last', models.PositiveIntegerField(default=14)),
                ('minimum_free_space_mb', models.PositiveIntegerField(default=1024)),
                ('scheduled_backups_enabled', models.BooleanField(default=False)),
                ('scheduled_backup_time', models.TimeField(default=datetime.time(2, 0))),
                ('scheduled_backup_profile', models.CharField(choices=[('full', 'Full Database'), ('business_critical', 'Business Critical'), ('subscribers', 'Subscribers'), ('billing_payments', 'Billing and Payments'), ('accounting', 'Accounting'), ('network_nms', 'Network and NMS'), ('settings_content', 'Settings and Content')], default='full', max_length=40)),
                ('weekly_backup_enabled', models.BooleanField(default=False)),
                ('remote_copy_enabled', models.BooleanField(default=False)),
                ('remote_backend', models.CharField(choices=[('none', 'None'), ('sftp', 'SFTP'), ('s3', 'S3-compatible')], default='none', max_length=20)),
                ('encryption_enabled', models.BooleanField(default=False)),
                ('backup_failure_alerts_enabled', models.BooleanField(default=True)),
                ('backup_stale_after_hours', models.PositiveIntegerField(default=36)),
                ('restore_test_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'permissions': [('view_backup_settings', 'Can view backup settings'), ('change_backup_settings', 'Can change backup settings')],
            },
        ),
    ]
