# Generated by Django 5.0.6 on 2026-04-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(help_text='IP address or hostname', max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('api_port', models.IntegerField(default=8728)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouterInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iface_type', models.CharField(choices=[('ether', 'Ethernet'), ('vlan', 'VLAN'), ('bridge', 'Bridge'), ('pppoe-in', 'PPPoE Session'), ('wg', 'WireGuard'), ('zerotier', 'ZeroTier'), ('loopback', 'Loopback'), ('other', 'Other')], default='other', max_length=30)),
                ('role', models.CharField(choices=[('uplink', 'Uplink'), ('olt', 'OLT'), ('libreqos', 'LibreQoS'), ('libreqos_mgmt', 'LibreQoS Management'), ('wifi', 'WiFi / Access Points'), ('pppoe', 'PPPoE'), ('dhcp', 'DHCP / IPoE'), ('management', 'Management'), ('client', 'Client'), ('pisowifi', 'PisoWifi'), ('other', 'Other')], default='other', max_length=30)),
                ('label', models.CharField(blank=True, help_text='Custom admin label', max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('actual_mtu', models.IntegerField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('is_slave', models.BooleanField(default=False)),
                ('is_dynamic', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='routers.router')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('router', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InterfaceTrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_bits_per_second', models.BigIntegerField(default=0)),
                ('tx_bits_per_second', models.BigIntegerField(default=0)),
                ('rx_packets_per_second', models.IntegerField(default=0)),
                ('tx_packets_per_second', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='routers.routerinterface')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
    ]
