# Generated by Django 5.0.6 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceTrafficCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_bits_per_second', models.BigIntegerField(default=0)),
                ('tx_bits_per_second', models.BigIntegerField(default=0)),
                ('rx_packets_per_second', models.IntegerField(default=0)),
                ('tx_packets_per_second', models.IntegerField(default=0)),
                ('activity_state', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('down', 'Down'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sampled_at', models.DateTimeField(auto_now=True)),
                ('interface', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='traffic_cache', to='routers.routerinterface')),
            ],
            options={
                'ordering': ['-sampled_at'],
            },
        ),
    ]
