# Generated by Django 5.0.6 on 2026-04-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0004_alter_subscriber_cutoff_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_label', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Mapped'), ('needs_review', 'Needs Review')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_attachments', to='subscribers.networknode')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_attachment', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['subscriber__username'],
            },
        ),
    ]
