# Generated by Django 5.0.6 on 2026-04-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0001_initial'),
        ('subscribers', '0004_alter_subscriber_cutoff_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('link_type', models.CharField(choices=[('fiber', 'Fiber'), ('ethernet', 'Ethernet'), ('wireless', 'Wireless Backhaul'), ('power', 'Power'), ('other', 'Other')], default='fiber', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_topology_links', to='subscribers.networknode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_topology_links', to='subscribers.networknode')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopologyLinkVertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertices', to='nms.topologylink')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('link', 'sequence')},
            },
        ),
    ]
