# Generated by Django 5.0.6 on 2026-04-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0002_topologylink_topologylinkvertex'),
        ('subscribers', '0004_alter_subscriber_cutoff_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('plc', 'PLC Splitter'), ('fbt', 'FBT Splitter'), ('patch_panel', 'Patch Panel'), ('splice_tray', 'Splice Tray'), ('other', 'Other')], default='other', max_length=30)),
                ('slot_label', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['parent_node__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('endpoint_type', models.CharField(choices=[('access', 'Access Port'), ('uplink', 'Uplink'), ('distribution', 'Distribution'), ('split_output', 'Split Output'), ('other', 'Other')], default='access', max_length=30)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('inactive', 'Inactive'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='subscribers.networknode')),
            ],
            options={
                'ordering': ['sequence', 'label', 'id'],
            },
        ),
        migrations.AddField(
            model_name='serviceattachment',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_attachments', to='nms.endpoint'),
        ),
        migrations.AddConstraint(
            model_name='serviceattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('endpoint__isnull', False)), fields=('endpoint',), name='nms_unique_active_attachment_per_endpoint'),
        ),
        migrations.AddField(
            model_name='internaldevice',
            name='parent_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_devices', to='subscribers.networknode'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='internal_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='nms.internaldevice'),
        ),
    ]
