# Generated by Django 5.0.6 on 2026-04-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0003_internaldevice_endpoint_serviceattachment_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldevice',
            name='auto_generate_plc_outputs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaldevice',
            name='plc_input_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internaldevice',
            name='plc_model',
            field=models.CharField(blank=True, choices=[('', 'Not a PLC'), ('1x4', '1x4'), ('1x8', '1x8'), ('1x16', '1x16'), ('1x32', '1x32')], max_length=10),
        ),
        migrations.AddField(
            model_name='internaldevice',
            name='plc_output_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
