# Generated by Django 5.0.6 on 2026-04-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0004_internaldevice_auto_generate_plc_outputs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('total_cores', models.PositiveIntegerField(default=0)),
                ('length_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installation_type', models.CharField(choices=[('aerial', 'Aerial'), ('underground', 'Underground'), ('indoor', 'Indoor'), ('mixed', 'Mixed')], default='aerial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('inactive', 'Inactive'), ('damaged', 'Damaged')], default='active', max_length=20)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cable', to='nms.topologylink')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CableCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('color_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('assignment_label', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='nms.cable')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('cable', 'sequence')},
            },
        ),
    ]
