# Generated by Django 5.0.6 on 2026-04-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0005_cable_cablecore'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldevice',
            name='auto_generate_fbt_outputs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaldevice',
            name='fbt_ratio',
            field=models.CharField(blank=True, choices=[('', 'Not an FBT'), ('70/30', '70/30'), ('80/20', '80/20'), ('90/10', '90/10')], max_length=10),
        ),
    ]
