# Generated by Codex on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0006_internaldevice_auto_generate_fbt_outputs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableCoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('used', 'Used')], default='used', max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_assignment', to='nms.cablecore')),
                ('service_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_assignments', to='nms.serviceattachment')),
            ],
            options={
                'ordering': ['core__cable__name', 'core__sequence', 'id'],
            },
        ),
    ]
