# Generated by Codex on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0007_cablecoreassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trace_type', models.CharField(choices=[('survey', 'Survey'), ('as_built', 'As Built'), ('maintenance', 'Maintenance'), ('outage', 'Outage'), ('other', 'Other')], default='survey', max_length=30)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GpsTracePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='nms.gpstrace')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('trace', 'sequence')},
            },
        ),
    ]
