# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0008_gpstrace_gpstracepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldevice',
            name='fbt_ratio',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Not an FBT'),
                    ('95/5', '95/5'),
                    ('90/10', '90/10'),
                    ('85/15', '85/15'),
                    ('80/20', '80/20'),
                    ('75/25', '75/25'),
                    ('70/30', '70/30'),
                    ('65/35', '65/35'),
                    ('60/40', '60/40'),
                    ('55/45', '55/45'),
                    ('50/50', '50/50'),
                ],
                max_length=10,
            ),
        ),
    ]
