# Generated by Django 5.0.6 on 2026-04-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0009_expand_fbt_ratio_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttachmentVertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('service_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertices', to='nms.serviceattachment')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('service_attachment', 'sequence')},
            },
        ),
    ]
