# Generated by Django 5.0.6 on 2026-04-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0010_serviceattachmentvertex'),
        ('routers', '0002_interfacetrafficcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='router_interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nms_endpoint', to='routers.routerinterface'),
        ),
        migrations.CreateModel(
            name='EndpointConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('fiber', 'Fiber'), ('ethernet', 'Ethernet'), ('patch', 'Patch Cord'), ('splice', 'Splice'), ('internal', 'Internal Wiring'), ('other', 'Other')], default='fiber', max_length=20)),
                ('role', models.CharField(choices=[('feeder', 'Feeder'), ('passthrough', 'Pass-through'), ('splitter_input', 'Splitter Input'), ('splitter_output', 'Splitter Output'), ('drop', 'Drop'), ('direct_client', 'Direct Client'), ('other', 'Other')], default='feeder', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('inactive', 'Inactive'), ('damaged', 'Damaged')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cable_core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint_connections', to='nms.cablecore')),
                ('downstream_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_connections', to='nms.endpoint')),
                ('topology_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint_connections', to='nms.topologylink')),
                ('upstream_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_connections', to='nms.endpoint')),
            ],
            options={
                'ordering': ['upstream_endpoint__label', 'downstream_endpoint__label', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='endpointconnection',
            constraint=models.UniqueConstraint(fields=('upstream_endpoint', 'downstream_endpoint'), name='uniq_nms_endpoint_connection_pair'),
        ),
        migrations.AddConstraint(
            model_name='endpointconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('downstream_endpoint',), name='uniq_nms_active_upstream_per_downstream_endpoint'),
        ),
    ]
