# Generated by Django 5.0.6 on 2026-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('new_subscriber', 'New Subscriber'), ('subscriber_status', 'Subscriber Status Change'), ('router_status', 'Router Status'), ('billing_generated', 'Billing Generated'), ('payment_received', 'Payment Received'), ('sms_sent', 'SMS Sent'), ('plan_change', 'Plan Change'), ('settings_change', 'Settings Change'), ('api_error', 'API Error'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
