# Generated by Django 5.0.6 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('system', 'System')], default='telegram', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_state',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
